services:
  next:
    container_name: bd_next_container
    build:
      context: ../../
      dockerfile: config/docker/next/Dockerfile
    expose:
      - "3000"
    volumes:
      - /app/node_modules
      - /app/.next
      - next_static:/static
    depends_on:
      - postgres
      - redis
    networks:
      - app-network
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: bd_nginx_container
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - next_static:/usr/share/nginx/html/_next/static
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - /home/user/certs:/etc/nginx/certs:ro
    depends_on:
      - next
    networks:
      - app-network
    restart: unless-stopped

  redis:
    container_name: redis-stack
    build: ./redis
    ports:
      - "6379"
    volumes:
      - redis-data:/data
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT:-6379}
    networks:
      - app-network
    restart: unless-stopped

  postgres:
    container_name: bd_postgres_container
    build: ./postgres/postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-123456}
      POSTGRES_DB: ${POSTGRES_DB:-postgres_db}
      PGDATA: ${PGDATA:-/data/postgres}
    volumes:
      - postgres:${PGDATA:-/data/postgres}
    ports:
      - '5432'
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  redis-data:
  postgres:
  next_static:
