# Use postgres/example user/password credentials
version: '3.5'

services:
  postgres:
    container_name: bd_postgres_container
    build: ./postgres/postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-123456}
      POSTGRES_DB: ${POSTGRES_DB:-postgres_db}
      PGDATA: ${PGDATA:-/data/postgres}
      DB_PORT: ${DB_PORT:-5432}
    volumes:
      - postgres:${PGDATA:-/data/postgres}
    ports:
      - '${DB_PORT:-5432}:5432'
    networks:
      - app-network
    restart: unless-stopped

  pgadmin:
    container_name: bd_pgadmin_container
    build: ./postgres/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-123456}
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - '${PGADMIN_PORT:-5050}:80'
    networks:
      - app-network
    restart: unless-stopped

  redis:
    container_name: bd_redis_container
    build: ./redis
    ports:
      - '${REDIS_PORT:-6379}:6379'
    volumes:
      - redis:/data
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  postgres:
  pgadmin:
  redis: