services:
  next:
    build:
      context: ../../
      dockerfile: config/docker/next/Dockerfile.dev
    volumes:
      - ../../:/app
      - D:/typescript/bd.tracker/node_modules:/app/node_modules
      - D:/typescript/bd.tracker/.next:/app/.next
    ports:
      - "3000:3000"
    environment:
      - USE_TURBOPACK=false #to use turbopack instead of webpack
    env_file:
      - ../../.env

  redis:
    ports:
      - "6379:6379"

  postgres:
    ports:
      - "5432:5432"

  nginx:
    volumes:
      - ./nginx/default-dev.conf:/etc/nginx/conf.d/default.conf:ro