FROM node:22-slim

ARG PORT=3000
ENV NEXT_TELEMETRY_DISABLED=1
ENV NODE_ENV=development
ENV HOME=/app
WORKDIR /app

# Install OpenSSL
RUN apt-get update -y && apt-get install -y openssl

EXPOSE $PORT
CMD if [ "$USE_TURBOPACK" = "true" ]; then \
    npm run dev -- --turbo; \
    else \
    npm run dev; \
    fi