import type { Metadata, Viewport } from 'next';

export const metadata: Metadata = {
  title: {
    default: 'BD tracker',
    template: `%s | BD tracker`,
  },
  description: 'Generated by create next app',
};

export const viewport: Viewport = {
  themeColor: '#FFFFFF',
  colorScheme: 'light',
  initialScale: 1,
  maximumScale: 1,
  minimumScale: 1,
};

export { App as default } from '@/app/App';
