version: '3.8'

services:
  redis:
    container_name: redis-stack
    build: ./redis  
    ports:
      - "6379:6379" 
    volumes:
      - redis-data:/data
    environment:
      - REDIS_PASSWORD=yourpassword 
    networks:
      - redis-network

networks:
  redis-network:
    driver: bridge

volumes:
  redis-data:
